import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavLayout from "@/components/shared/navbar/NavLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "grocery",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="light">
      <body className={inter.className}>
        <NavLayout></NavLayout>
        <div className="w-[90%] mx-auto">{children}</div>
      </body>
    </html>
  );
}
